services:
  - type: web
    name: p-bot-service
    env: node
    plan: free
    buildCommand: pnpm install # ou npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.16.0
      - key: TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
